/*
 * main.c — Entry point for bare-metal Lean programs
 *
 * This is the C main() called from boot.S after hardware init.
 * It initializes the UART, the Lean runtime, the compiled Lean module,
 * and then calls the Lean main function.
 */

#include "board.h"
#include "lean_rt.h"
#include "uart.h"

/* These symbols are generated by `lean -c` from the Lean source.
 * The exact names depend on the module. For examples/hello.lean
 * with no module declaration, Lean generates:
 *   - initialize_Main(...)  — module initializer
 *   - _lean_main(...)       — the main function
 */
extern lean_object *initialize_Main(uint8_t builtin, lean_object *w);
extern lean_object *_lean_main(lean_object *w);

static void fatal_lean_error(const char *msg, lean_object *res)
{
    uart_puts("FATAL: ");
    uart_puts(msg);
    uart_putc('\n');
    if (res != 0)
        lean_io_result_show_error(res);
    board_halt();
}

int main(void)
{
    board_early_init();
    uart_init();
    uart_puts("lean4-baremetal: booting...\n");
    uart_puts("board: ");
    uart_puts(board_name());
    uart_putc('\n');

    /* Initialize the Lean runtime */
    lean_object *res;

    res = lean_initialize_runtime_module();
    if (lean_io_result_is_error(res))
        fatal_lean_error("lean_initialize_runtime_module failed", res);
    lean_dec(res);

    /* Initialize the task manager (no-op on bare-metal) */
    res = lean_init_task_manager();
    if (lean_io_result_is_error(res))
        fatal_lean_error("lean_init_task_manager failed", res);
    lean_dec(res);

    lean_set_panic_messages(0);

    /* Initialize the Lean module (generated code) */
    res = initialize_Main(1 /* builtin */, lean_box(0) /* world */);
    if (lean_io_result_is_error(res))
        fatal_lean_error("initialize_Main failed", res);
    lean_dec(res);

    lean_set_panic_messages(1);
    lean_io_mark_end_initialization();

    /* Call the Lean main function */
    res = _lean_main(lean_box(0) /* world */);
    if (lean_io_result_is_error(res)) {
        fatal_lean_error("Lean main returned error", res);
    }
    lean_dec(res);

    uart_puts("lean4-baremetal: done.\n");
    return 0;
}
