/*
 * main.c — Entry point for bare-metal Lean programs
 *
 * This is the C main() called from boot.S after hardware init.
 * It initializes the UART, the Lean runtime, the compiled Lean module,
 * and then calls the Lean main function.
 */

#include "lean_rt.h"
#include "uart.h"

extern void abort(void) __attribute__((noreturn));

/* These symbols are generated by `lean -c` from the Lean source.
 * The exact names depend on the module. For examples/hello.lean
 * with no module declaration, Lean generates:
 *   - initialize_Main(...)  — module initializer
 *   - _lean_main(...)       — the main function
 */
extern lean_object *initialize_Main(uint8_t builtin, lean_object *w);
extern lean_object *_lean_main(lean_object *w);

int main(void)
{
    uart_init();
    uart_puts("lean4-baremetal: booting...\n");

    /* Initialize the Lean runtime */
    lean_object *res;

    res = lean_initialize_runtime_module();
    if (lean_io_result_is_error(res)) {
        uart_puts("FATAL: lean_initialize_runtime_module failed\n");
        lean_io_result_show_error(res);
        abort();
    }
    lean_dec(res);

    /* Initialize the task manager (no-op on bare-metal) */
    res = lean_init_task_manager();
    if (lean_io_result_is_error(res)) {
        uart_puts("FATAL: lean_init_task_manager failed\n");
        lean_io_result_show_error(res);
        abort();
    }
    lean_dec(res);

    lean_set_panic_messages(0);

    /* Initialize the Lean module (generated code) */
    res = initialize_Main(1 /* builtin */, lean_box(0) /* world */);
    if (lean_io_result_is_error(res)) {
        uart_puts("FATAL: initialize_Main failed\n");
        lean_io_result_show_error(res);
        abort();
    }
    lean_dec(res);

    lean_set_panic_messages(1);
    lean_io_mark_end_initialization();

    /* Call the Lean main function */
    res = _lean_main(lean_box(0) /* world */);
    if (lean_io_result_is_error(res)) {
        uart_puts("ERROR: Lean main returned error\n");
        lean_io_result_show_error(res);
        lean_dec(res);
        return 1;
    }
    lean_dec(res);

    uart_puts("lean4-baremetal: done.\n");
    return 0;
}
